### PR TITLE
LIFFT robustness improvement

### PR DESCRIPTION
**Pull request by rhiju**
restoring old leasqr (rather than super-slow robust_fit) as default fitt...ing tool. 
To make fit robust, adding a prior that start and end fraction folded should be 1.0 and 0.0!

@dimenwarper  Can you check out this branch, and send me your comments? 
This seems to strongly regularize fits to Ann's hairping melting data with negligible effect on speed. 
Would you mind trying on your Tebowned titrations? If OK, can you put your thumbs up here? If not, can you send me a note on what happens?

### CODE REVIEW

**Comment by dimenwarper** [comment]
I get lots of warnings with the new fitting, e.g.

Warning: Matrix is close to singular or badly scaled.
         Results may be inaccurate.

And fitting on a region of Tebowned wild type with its most changing
reactivities I get a weird likelihood shape, compared to robust_fit, see
below.


Will think about it and see if I can come up with a fix.

Pablo

**Comment by rhiju** [comment]
Thanks a lot for checking. I’m out of town, but perhaps when I get back and you have time, let’s look over this together on your data for an hour before updating/merging. Not urgent.

By the way, the image didn’t show up in the e-mail — can you send again? You may have to ‘pretend upload’ the image into a new issue, and then copy the aws link into here.

**Comment by dimenwarper** [comment]
Sure, here are the images uploaded as attachments

**Comment by dimenwarper** [comment]
Ack, didn't show up! Trying again....
regularize_endpoints
robust_fit

**Pull request merged**
